// SPDX-License-Identifier: Apache-2.0

//Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: carisma/node/v1/node.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentConfiguration_StateType int32

const (
	DeploymentConfiguration_STATE_TYPE_DESIRED DeploymentConfiguration_StateType = 0
	DeploymentConfiguration_STATE_TYPE_ACTUAL  DeploymentConfiguration_StateType = 1
)

// Enum value maps for DeploymentConfiguration_StateType.
var (
	DeploymentConfiguration_StateType_name = map[int32]string{
		0: "STATE_TYPE_DESIRED",
		1: "STATE_TYPE_ACTUAL",
	}
	DeploymentConfiguration_StateType_value = map[string]int32{
		"STATE_TYPE_DESIRED": 0,
		"STATE_TYPE_ACTUAL":  1,
	}
)

func (x DeploymentConfiguration_StateType) Enum() *DeploymentConfiguration_StateType {
	p := new(DeploymentConfiguration_StateType)
	*p = x
	return p
}

func (x DeploymentConfiguration_StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentConfiguration_StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_carisma_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (DeploymentConfiguration_StateType) Type() protoreflect.EnumType {
	return &file_carisma_node_v1_node_proto_enumTypes[0]
}

func (x DeploymentConfiguration_StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentConfiguration_StateType.Descriptor instead.
func (DeploymentConfiguration_StateType) EnumDescriptor() ([]byte, []int) {
	return file_carisma_node_v1_node_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carisma_node_v1_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carisma_node_v1_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_carisma_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carisma_node_v1_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carisma_node_v1_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_carisma_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeploymentConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json      string                            `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	StateType DeploymentConfiguration_StateType `protobuf:"varint,2,opt,name=state_type,json=stateType,proto3,enum=carisma.node.v1.DeploymentConfiguration_StateType" json:"state_type,omitempty"`
}

func (x *DeploymentConfiguration) Reset() {
	*x = DeploymentConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carisma_node_v1_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentConfiguration) ProtoMessage() {}

func (x *DeploymentConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_carisma_node_v1_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentConfiguration.ProtoReflect.Descriptor instead.
func (*DeploymentConfiguration) Descriptor() ([]byte, []int) {
	return file_carisma_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentConfiguration) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *DeploymentConfiguration) GetStateType() DeploymentConfiguration_StateType {
	if x != nil {
		return x.StateType
	}
	return DeploymentConfiguration_STATE_TYPE_DESIRED
}

var File_carisma_node_v1_node_proto protoreflect.FileDescriptor

var file_carisma_node_v1_node_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x61, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x61,
	0x72, 0x69, 0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x3f, 0x0a,
	0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x22,
	0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73,
	0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x61,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x44, 0x45, 0x53, 0x49, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x55, 0x41, 0x4c, 0x10,
	0x01, 0x32, 0xcd, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x61, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d,
	0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x28, 0x2e, 0x63, 0x61, 0x72, 0x69,
	0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x28, 0x2e, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x60, 0x5a, 0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x64, 0x65, 0x73, 0x2d, 0x62, 0x65, 0x6e, 0x7a, 0x2f, 0x63, 0x61,
	0x72, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x63, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x61, 0x2f, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_carisma_node_v1_node_proto_rawDescOnce sync.Once
	file_carisma_node_v1_node_proto_rawDescData = file_carisma_node_v1_node_proto_rawDesc
)

func file_carisma_node_v1_node_proto_rawDescGZIP() []byte {
	file_carisma_node_v1_node_proto_rawDescOnce.Do(func() {
		file_carisma_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_carisma_node_v1_node_proto_rawDescData)
	})
	return file_carisma_node_v1_node_proto_rawDescData
}

var file_carisma_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carisma_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carisma_node_v1_node_proto_goTypes = []interface{}{
	(DeploymentConfiguration_StateType)(0), // 0: carisma.node.v1.DeploymentConfiguration.StateType
	(*RegisterRequest)(nil),                // 1: carisma.node.v1.RegisterRequest
	(*RegisterResponse)(nil),               // 2: carisma.node.v1.RegisterResponse
	(*DeploymentConfiguration)(nil),        // 3: carisma.node.v1.DeploymentConfiguration
}
var file_carisma_node_v1_node_proto_depIdxs = []int32{
	0, // 0: carisma.node.v1.DeploymentConfiguration.state_type:type_name -> carisma.node.v1.DeploymentConfiguration.StateType
	1, // 1: carisma.node.v1.NodeRegistryService.Register:input_type -> carisma.node.v1.RegisterRequest
	3, // 2: carisma.node.v1.NodeRegistryService.OpenChannel:input_type -> carisma.node.v1.DeploymentConfiguration
	2, // 3: carisma.node.v1.NodeRegistryService.Register:output_type -> carisma.node.v1.RegisterResponse
	3, // 4: carisma.node.v1.NodeRegistryService.OpenChannel:output_type -> carisma.node.v1.DeploymentConfiguration
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carisma_node_v1_node_proto_init() }
func file_carisma_node_v1_node_proto_init() {
	if File_carisma_node_v1_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_carisma_node_v1_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carisma_node_v1_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carisma_node_v1_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carisma_node_v1_node_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carisma_node_v1_node_proto_goTypes,
		DependencyIndexes: file_carisma_node_v1_node_proto_depIdxs,
		EnumInfos:         file_carisma_node_v1_node_proto_enumTypes,
		MessageInfos:      file_carisma_node_v1_node_proto_msgTypes,
	}.Build()
	File_carisma_node_v1_node_proto = out.File
	file_carisma_node_v1_node_proto_rawDesc = nil
	file_carisma_node_v1_node_proto_goTypes = nil
	file_carisma_node_v1_node_proto_depIdxs = nil
}
