// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: adapter.proto
#ifndef GRPC_adapter_2eproto__INCLUDED
#define GRPC_adapter_2eproto__INCLUDED

#include "adapter.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace com {
namespace mercedes_benz {
namespace csa {

class Adapter final {
 public:
  static constexpr char const* service_full_name() {
    return "com.mercedes_benz.csa.Adapter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::com::mercedes_benz::csa::Services* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>> AsyncGetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>>(AsyncGetAvailableServicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>> PrepareAsyncGetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>>(PrepareAsyncGetAvailableServicesRaw(context, request, cq));
    }
    virtual ::grpc::Status CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::com::mercedes_benz::csa::MethodCallResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>> AsyncCallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>>(AsyncCallMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>> PrepareAsyncCallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>>(PrepareAsyncCallMethodRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>* AsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::Services>* PrepareAsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>* AsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::mercedes_benz::csa::MethodCallResponse>* PrepareAsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::com::mercedes_benz::csa::Services* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>> AsyncGetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>>(AsyncGetAvailableServicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>> PrepareAsyncGetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>>(PrepareAsyncGetAvailableServicesRaw(context, request, cq));
    }
    ::grpc::Status CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::com::mercedes_benz::csa::MethodCallResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>> AsyncCallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>>(AsyncCallMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>> PrepareAsyncCallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>>(PrepareAsyncCallMethodRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, std::function<void(::grpc::Status)>) override;
      void GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, std::function<void(::grpc::Status)>) override;
      void CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>* AsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>* PrepareAsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>* AsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>* PrepareAsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAvailableServices_;
    const ::grpc::internal::RpcMethod rpcmethod_CallMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetAvailableServices(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response);
    virtual ::grpc::Status CallMethod(::grpc::ServerContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvailableServices(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::com::mercedes_benz::csa::Services>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallMethod() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallMethod(::grpc::ServerContext* context, ::com::mercedes_benz::csa::Method* request, ::grpc::ServerAsyncResponseWriter< ::com::mercedes_benz::csa::MethodCallResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAvailableServices<WithAsyncMethod_CallMethod<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response) { return this->GetAvailableServices(context, request, response); }));}
    void SetMessageAllocatorFor_GetAvailableServices(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvailableServices(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CallMethod() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response) { return this->CallMethod(context, request, response); }));}
    void SetMessageAllocatorFor_CallMethod(
        ::grpc::MessageAllocator< ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetAvailableServices<WithCallbackMethod_CallMethod<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallMethod() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAvailableServices(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallMethod() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAvailableServices(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAvailableServices(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CallMethod() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CallMethod(context, request, response); }));
    }
    ~WithRawCallbackMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAvailableServices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAvailableServices() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services>* streamer) {
                       return this->StreamedGetAvailableServices(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAvailableServices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAvailableServices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::com::mercedes_benz::csa::Services* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAvailableServices(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::com::mercedes_benz::csa::Services>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CallMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CallMethod() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse>* streamer) {
                       return this->StreamedCallMethod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CallMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallMethod(::grpc::ServerContext* /*context*/, const ::com::mercedes_benz::csa::Method* /*request*/, ::com::mercedes_benz::csa::MethodCallResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCallMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::com::mercedes_benz::csa::Method,::com::mercedes_benz::csa::MethodCallResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAvailableServices<WithStreamedUnaryMethod_CallMethod<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAvailableServices<WithStreamedUnaryMethod_CallMethod<Service > > StreamedService;
};

}  // namespace csa
}  // namespace mercedes_benz
}  // namespace com


#endif  // GRPC_adapter_2eproto__INCLUDED
