// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: adapter.proto
// Protobuf C++ Version: 5.27.2

#include "adapter.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace com {
namespace mercedes_benz {
namespace csa {

inline constexpr Service::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : service_id_{0},
        instance_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Service::Service(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServiceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceDefaultTypeInternal() {}
  union {
    Service _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceDefaultTypeInternal _Service_default_instance_;

inline constexpr MethodCallResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MethodCallResponse::MethodCallResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MethodCallResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MethodCallResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MethodCallResponseDefaultTypeInternal() {}
  union {
    MethodCallResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MethodCallResponseDefaultTypeInternal _MethodCallResponse_default_instance_;

inline constexpr Services::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : services_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Services::Services(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServicesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServicesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServicesDefaultTypeInternal() {}
  union {
    Services _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServicesDefaultTypeInternal _Services_default_instance_;

inline constexpr Method::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        service_{nullptr},
        method_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Method::Method(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MethodDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MethodDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MethodDefaultTypeInternal() {}
  union {
    Method _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MethodDefaultTypeInternal _Method_default_instance_;
}  // namespace csa
}  // namespace mercedes_benz
}  // namespace com
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_adapter_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_adapter_2eproto = nullptr;
const ::uint32_t
    TableStruct_adapter_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Service, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Service, _impl_.service_id_),
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Service, _impl_.instance_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Services, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Services, _impl_.services_),
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Method, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Method, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Method, _impl_.service_),
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Method, _impl_.method_id_),
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::Method, _impl_.data_),
        0,
        ~0u,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::MethodCallResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::mercedes_benz::csa::MethodCallResponse, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::com::mercedes_benz::csa::Service)},
        {10, -1, -1, sizeof(::com::mercedes_benz::csa::Services)},
        {19, 30, -1, sizeof(::com::mercedes_benz::csa::Method)},
        {33, -1, -1, sizeof(::com::mercedes_benz::csa::MethodCallResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::com::mercedes_benz::csa::_Service_default_instance_._instance,
    &::com::mercedes_benz::csa::_Services_default_instance_._instance,
    &::com::mercedes_benz::csa::_Method_default_instance_._instance,
    &::com::mercedes_benz::csa::_MethodCallResponse_default_instance_._instance,
};
const char descriptor_table_protodef_adapter_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\radapter.proto\022\025com.mercedes_benz.csa\032\033"
    "google/protobuf/empty.proto\"2\n\007Service\022\022"
    "\n\nservice_id\030\001 \001(\005\022\023\n\013instance_id\030\002 \001(\005\""
    "<\n\010Services\0220\n\010services\030\001 \003(\0132\036.com.merc"
    "edes_benz.csa.Service\"Z\n\006Method\022/\n\007servi"
    "ce\030\001 \001(\0132\036.com.mercedes_benz.csa.Service"
    "\022\021\n\tmethod_id\030\002 \001(\005\022\014\n\004data\030\003 \001(\014\"\"\n\022Met"
    "hodCallResponse\022\014\n\004data\030\001 \001(\0142\266\001\n\007Adapte"
    "r\022Q\n\024GetAvailableServices\022\026.google.proto"
    "buf.Empty\032\037.com.mercedes_benz.csa.Servic"
    "es\"\000\022X\n\nCallMethod\022\035.com.mercedes_benz.c"
    "sa.Method\032).com.mercedes_benz.csa.Method"
    "CallResponse\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_adapter_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_adapter_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_adapter_2eproto = {
    false,
    false,
    502,
    descriptor_table_protodef_adapter_2eproto,
    "adapter.proto",
    &descriptor_table_adapter_2eproto_once,
    descriptor_table_adapter_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_adapter_2eproto::offsets,
    file_level_enum_descriptors_adapter_2eproto,
    file_level_service_descriptors_adapter_2eproto,
};
namespace com {
namespace mercedes_benz {
namespace csa {
// ===================================================================

class Service::_Internal {
 public:
};

Service::Service(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.mercedes_benz.csa.Service)
}
Service::Service(
    ::google::protobuf::Arena* arena, const Service& from)
    : Service(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Service::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Service::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, service_id_),
           0,
           offsetof(Impl_, instance_id_) -
               offsetof(Impl_, service_id_) +
               sizeof(Impl_::instance_id_));
}
Service::~Service() {
  // @@protoc_insertion_point(destructor:com.mercedes_benz.csa.Service)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Service::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Service::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Service, _impl_._cached_size_),
              false,
          },
          &Service::MergeImpl,
          &Service::kDescriptorMethods,
          &descriptor_table_adapter_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Service::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Service_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::Service>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 instance_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Service, _impl_.instance_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Service, _impl_.instance_id_)}},
    // int32 service_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Service, _impl_.service_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Service, _impl_.service_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 service_id = 1;
    {PROTOBUF_FIELD_OFFSET(Service, _impl_.service_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 instance_id = 2;
    {PROTOBUF_FIELD_OFFSET(Service, _impl_.instance_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Service::Clear() {
// @@protoc_insertion_point(message_clear_start:com.mercedes_benz.csa.Service)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.service_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.instance_id_) -
      reinterpret_cast<char*>(&_impl_.service_id_)) + sizeof(_impl_.instance_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Service::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.mercedes_benz.csa.Service)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 service_id = 1;
  if (this->_internal_service_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_service_id(), target);
  }

  // int32 instance_id = 2;
  if (this->_internal_instance_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_instance_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.mercedes_benz.csa.Service)
  return target;
}

::size_t Service::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.mercedes_benz.csa.Service)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 service_id = 1;
  if (this->_internal_service_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_service_id());
  }

  // int32 instance_id = 2;
  if (this->_internal_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_instance_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Service::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Service*>(&to_msg);
  auto& from = static_cast<const Service&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.mercedes_benz.csa.Service)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_service_id() != 0) {
    _this->_impl_.service_id_ = from._impl_.service_id_;
  }
  if (from._internal_instance_id() != 0) {
    _this->_impl_.instance_id_ = from._impl_.instance_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Service::CopyFrom(const Service& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.mercedes_benz.csa.Service)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Service::InternalSwap(Service* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Service, _impl_.instance_id_)
      + sizeof(Service::_impl_.instance_id_)
      - PROTOBUF_FIELD_OFFSET(Service, _impl_.service_id_)>(
          reinterpret_cast<char*>(&_impl_.service_id_),
          reinterpret_cast<char*>(&other->_impl_.service_id_));
}

::google::protobuf::Metadata Service::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Services::_Internal {
 public:
};

Services::Services(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.mercedes_benz.csa.Services)
}
inline PROTOBUF_NDEBUG_INLINE Services::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::mercedes_benz::csa::Services& from_msg)
      : services_{visibility, arena, from.services_},
        _cached_size_{0} {}

Services::Services(
    ::google::protobuf::Arena* arena,
    const Services& from)
    : ::google::protobuf::Message(arena) {
  Services* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:com.mercedes_benz.csa.Services)
}
inline PROTOBUF_NDEBUG_INLINE Services::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : services_{visibility, arena},
        _cached_size_{0} {}

inline void Services::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Services::~Services() {
  // @@protoc_insertion_point(destructor:com.mercedes_benz.csa.Services)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Services::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Services::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Services, _impl_._cached_size_),
              false,
          },
          &Services::MergeImpl,
          &Services::kDescriptorMethods,
          &descriptor_table_adapter_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Services::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Services_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::Services>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .com.mercedes_benz.csa.Service services = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Services, _impl_.services_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .com.mercedes_benz.csa.Service services = 1;
    {PROTOBUF_FIELD_OFFSET(Services, _impl_.services_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::Service>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Services::Clear() {
// @@protoc_insertion_point(message_clear_start:com.mercedes_benz.csa.Services)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.services_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Services::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.mercedes_benz.csa.Services)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .com.mercedes_benz.csa.Service services = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_services_size());
       i < n; i++) {
    const auto& repfield = this->_internal_services().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.mercedes_benz.csa.Services)
  return target;
}

::size_t Services::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.mercedes_benz.csa.Services)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .com.mercedes_benz.csa.Service services = 1;
  total_size += 1UL * this->_internal_services_size();
  for (const auto& msg : this->_internal_services()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Services::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Services*>(&to_msg);
  auto& from = static_cast<const Services&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.mercedes_benz.csa.Services)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_services()->MergeFrom(
      from._internal_services());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Services::CopyFrom(const Services& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.mercedes_benz.csa.Services)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Services::InternalSwap(Services* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.services_.InternalSwap(&other->_impl_.services_);
}

::google::protobuf::Metadata Services::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Method::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Method>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Method, _impl_._has_bits_);
};

Method::Method(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.mercedes_benz.csa.Method)
}
inline PROTOBUF_NDEBUG_INLINE Method::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::mercedes_benz::csa::Method& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_(arena, from.data_) {}

Method::Method(
    ::google::protobuf::Arena* arena,
    const Method& from)
    : ::google::protobuf::Message(arena) {
  Method* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.service_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::com::mercedes_benz::csa::Service>(
                              arena, *from._impl_.service_)
                        : nullptr;
  _impl_.method_id_ = from._impl_.method_id_;

  // @@protoc_insertion_point(copy_constructor:com.mercedes_benz.csa.Method)
}
inline PROTOBUF_NDEBUG_INLINE Method::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        data_(arena) {}

inline void Method::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, service_),
           0,
           offsetof(Impl_, method_id_) -
               offsetof(Impl_, service_) +
               sizeof(Impl_::method_id_));
}
Method::~Method() {
  // @@protoc_insertion_point(destructor:com.mercedes_benz.csa.Method)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Method::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_.Destroy();
  delete _impl_.service_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Method::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Method, _impl_._cached_size_),
              false,
          },
          &Method::MergeImpl,
          &Method::kDescriptorMethods,
          &descriptor_table_adapter_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> Method::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Method, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Method_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::Method>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .com.mercedes_benz.csa.Service service = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Method, _impl_.service_)}},
    // int32 method_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Method, _impl_.method_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Method, _impl_.method_id_)}},
    // bytes data = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Method, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .com.mercedes_benz.csa.Service service = 1;
    {PROTOBUF_FIELD_OFFSET(Method, _impl_.service_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 method_id = 2;
    {PROTOBUF_FIELD_OFFSET(Method, _impl_.method_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes data = 3;
    {PROTOBUF_FIELD_OFFSET(Method, _impl_.data_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::Service>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Method::Clear() {
// @@protoc_insertion_point(message_clear_start:com.mercedes_benz.csa.Method)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.service_ != nullptr);
    _impl_.service_->Clear();
  }
  _impl_.method_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Method::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.mercedes_benz.csa.Method)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .com.mercedes_benz.csa.Service service = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.service_, _impl_.service_->GetCachedSize(), target, stream);
  }

  // int32 method_id = 2;
  if (this->_internal_method_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_method_id(), target);
  }

  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.mercedes_benz.csa.Method)
  return target;
}

::size_t Method::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.mercedes_benz.csa.Method)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_data());
  }

  // .com.mercedes_benz.csa.Service service = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.service_);
  }

  // int32 method_id = 2;
  if (this->_internal_method_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_method_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Method::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Method*>(&to_msg);
  auto& from = static_cast<const Method&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:com.mercedes_benz.csa.Method)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.service_ != nullptr);
    if (_this->_impl_.service_ == nullptr) {
      _this->_impl_.service_ =
          ::google::protobuf::Message::CopyConstruct<::com::mercedes_benz::csa::Service>(arena, *from._impl_.service_);
    } else {
      _this->_impl_.service_->MergeFrom(*from._impl_.service_);
    }
  }
  if (from._internal_method_id() != 0) {
    _this->_impl_.method_id_ = from._impl_.method_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Method::CopyFrom(const Method& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.mercedes_benz.csa.Method)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Method::InternalSwap(Method* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Method, _impl_.method_id_)
      + sizeof(Method::_impl_.method_id_)
      - PROTOBUF_FIELD_OFFSET(Method, _impl_.service_)>(
          reinterpret_cast<char*>(&_impl_.service_),
          reinterpret_cast<char*>(&other->_impl_.service_));
}

::google::protobuf::Metadata Method::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MethodCallResponse::_Internal {
 public:
};

MethodCallResponse::MethodCallResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.mercedes_benz.csa.MethodCallResponse)
}
inline PROTOBUF_NDEBUG_INLINE MethodCallResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::mercedes_benz::csa::MethodCallResponse& from_msg)
      : data_(arena, from.data_),
        _cached_size_{0} {}

MethodCallResponse::MethodCallResponse(
    ::google::protobuf::Arena* arena,
    const MethodCallResponse& from)
    : ::google::protobuf::Message(arena) {
  MethodCallResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:com.mercedes_benz.csa.MethodCallResponse)
}
inline PROTOBUF_NDEBUG_INLINE MethodCallResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void MethodCallResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MethodCallResponse::~MethodCallResponse() {
  // @@protoc_insertion_point(destructor:com.mercedes_benz.csa.MethodCallResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MethodCallResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MethodCallResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MethodCallResponse, _impl_._cached_size_),
              false,
          },
          &MethodCallResponse::MergeImpl,
          &MethodCallResponse::kDescriptorMethods,
          &descriptor_table_adapter_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> MethodCallResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MethodCallResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::mercedes_benz::csa::MethodCallResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MethodCallResponse, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes data = 1;
    {PROTOBUF_FIELD_OFFSET(MethodCallResponse, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MethodCallResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:com.mercedes_benz.csa.MethodCallResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MethodCallResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.mercedes_benz.csa.MethodCallResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.mercedes_benz.csa.MethodCallResponse)
  return target;
}

::size_t MethodCallResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.mercedes_benz.csa.MethodCallResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MethodCallResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MethodCallResponse*>(&to_msg);
  auto& from = static_cast<const MethodCallResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.mercedes_benz.csa.MethodCallResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MethodCallResponse::CopyFrom(const MethodCallResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.mercedes_benz.csa.MethodCallResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MethodCallResponse::InternalSwap(MethodCallResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata MethodCallResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace csa
}  // namespace mercedes_benz
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_adapter_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
