// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: adapter.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_adapter_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_adapter_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_adapter_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_adapter_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_adapter_2eproto;
namespace com {
namespace mercedes_benz {
namespace csa {
class Method;
struct MethodDefaultTypeInternal;
extern MethodDefaultTypeInternal _Method_default_instance_;
class MethodCallResponse;
struct MethodCallResponseDefaultTypeInternal;
extern MethodCallResponseDefaultTypeInternal _MethodCallResponse_default_instance_;
class Service;
struct ServiceDefaultTypeInternal;
extern ServiceDefaultTypeInternal _Service_default_instance_;
class Services;
struct ServicesDefaultTypeInternal;
extern ServicesDefaultTypeInternal _Services_default_instance_;
}  // namespace csa
}  // namespace mercedes_benz
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace com {
namespace mercedes_benz {
namespace csa {

// ===================================================================


// -------------------------------------------------------------------

class Service final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.mercedes_benz.csa.Service) */ {
 public:
  inline Service() : Service(nullptr) {}
  ~Service() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Service(
      ::google::protobuf::internal::ConstantInitialized);

  inline Service(const Service& from) : Service(nullptr, from) {}
  inline Service(Service&& from) noexcept
      : Service(nullptr, std::move(from)) {}
  inline Service& operator=(const Service& from) {
    CopyFrom(from);
    return *this;
  }
  inline Service& operator=(Service&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Service& default_instance() {
    return *internal_default_instance();
  }
  static inline const Service* internal_default_instance() {
    return reinterpret_cast<const Service*>(
        &_Service_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Service& a, Service& b) { a.Swap(&b); }
  inline void Swap(Service* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Service* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Service* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Service>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Service& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Service& from) { Service::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Service* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.mercedes_benz.csa.Service"; }

 protected:
  explicit Service(::google::protobuf::Arena* arena);
  Service(::google::protobuf::Arena* arena, const Service& from);
  Service(::google::protobuf::Arena* arena, Service&& from) noexcept
      : Service(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceIdFieldNumber = 1,
    kInstanceIdFieldNumber = 2,
  };
  // int32 service_id = 1;
  void clear_service_id() ;
  ::int32_t service_id() const;
  void set_service_id(::int32_t value);

  private:
  ::int32_t _internal_service_id() const;
  void _internal_set_service_id(::int32_t value);

  public:
  // int32 instance_id = 2;
  void clear_instance_id() ;
  ::int32_t instance_id() const;
  void set_instance_id(::int32_t value);

  private:
  ::int32_t _internal_instance_id() const;
  void _internal_set_instance_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:com.mercedes_benz.csa.Service)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Service_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Service& from_msg);
    ::int32_t service_id_;
    ::int32_t instance_id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adapter_2eproto;
};
// -------------------------------------------------------------------

class MethodCallResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.mercedes_benz.csa.MethodCallResponse) */ {
 public:
  inline MethodCallResponse() : MethodCallResponse(nullptr) {}
  ~MethodCallResponse() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MethodCallResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline MethodCallResponse(const MethodCallResponse& from) : MethodCallResponse(nullptr, from) {}
  inline MethodCallResponse(MethodCallResponse&& from) noexcept
      : MethodCallResponse(nullptr, std::move(from)) {}
  inline MethodCallResponse& operator=(const MethodCallResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MethodCallResponse& operator=(MethodCallResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MethodCallResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MethodCallResponse* internal_default_instance() {
    return reinterpret_cast<const MethodCallResponse*>(
        &_MethodCallResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MethodCallResponse& a, MethodCallResponse& b) { a.Swap(&b); }
  inline void Swap(MethodCallResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MethodCallResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MethodCallResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<MethodCallResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MethodCallResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MethodCallResponse& from) { MethodCallResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MethodCallResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.mercedes_benz.csa.MethodCallResponse"; }

 protected:
  explicit MethodCallResponse(::google::protobuf::Arena* arena);
  MethodCallResponse(::google::protobuf::Arena* arena, const MethodCallResponse& from);
  MethodCallResponse(::google::protobuf::Arena* arena, MethodCallResponse&& from) noexcept
      : MethodCallResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:com.mercedes_benz.csa.MethodCallResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MethodCallResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MethodCallResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr data_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adapter_2eproto;
};
// -------------------------------------------------------------------

class Services final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.mercedes_benz.csa.Services) */ {
 public:
  inline Services() : Services(nullptr) {}
  ~Services() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Services(
      ::google::protobuf::internal::ConstantInitialized);

  inline Services(const Services& from) : Services(nullptr, from) {}
  inline Services(Services&& from) noexcept
      : Services(nullptr, std::move(from)) {}
  inline Services& operator=(const Services& from) {
    CopyFrom(from);
    return *this;
  }
  inline Services& operator=(Services&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Services& default_instance() {
    return *internal_default_instance();
  }
  static inline const Services* internal_default_instance() {
    return reinterpret_cast<const Services*>(
        &_Services_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Services& a, Services& b) { a.Swap(&b); }
  inline void Swap(Services* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Services* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Services* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Services>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Services& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Services& from) { Services::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Services* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.mercedes_benz.csa.Services"; }

 protected:
  explicit Services(::google::protobuf::Arena* arena);
  Services(::google::protobuf::Arena* arena, const Services& from);
  Services(::google::protobuf::Arena* arena, Services&& from) noexcept
      : Services(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServicesFieldNumber = 1,
  };
  // repeated .com.mercedes_benz.csa.Service services = 1;
  int services_size() const;
  private:
  int _internal_services_size() const;

  public:
  void clear_services() ;
  ::com::mercedes_benz::csa::Service* mutable_services(int index);
  ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>* mutable_services();

  private:
  const ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>& _internal_services() const;
  ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>* _internal_mutable_services();
  public:
  const ::com::mercedes_benz::csa::Service& services(int index) const;
  ::com::mercedes_benz::csa::Service* add_services();
  const ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>& services() const;
  // @@protoc_insertion_point(class_scope:com.mercedes_benz.csa.Services)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Services_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Services& from_msg);
    ::google::protobuf::RepeatedPtrField< ::com::mercedes_benz::csa::Service > services_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adapter_2eproto;
};
// -------------------------------------------------------------------

class Method final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.mercedes_benz.csa.Method) */ {
 public:
  inline Method() : Method(nullptr) {}
  ~Method() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Method(
      ::google::protobuf::internal::ConstantInitialized);

  inline Method(const Method& from) : Method(nullptr, from) {}
  inline Method(Method&& from) noexcept
      : Method(nullptr, std::move(from)) {}
  inline Method& operator=(const Method& from) {
    CopyFrom(from);
    return *this;
  }
  inline Method& operator=(Method&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Method& default_instance() {
    return *internal_default_instance();
  }
  static inline const Method* internal_default_instance() {
    return reinterpret_cast<const Method*>(
        &_Method_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Method& a, Method& b) { a.Swap(&b); }
  inline void Swap(Method* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Method* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Method* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Method>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Method& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Method& from) { Method::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Method* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.mercedes_benz.csa.Method"; }

 protected:
  explicit Method(::google::protobuf::Arena* arena);
  Method(::google::protobuf::Arena* arena, const Method& from);
  Method(::google::protobuf::Arena* arena, Method&& from) noexcept
      : Method(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 3,
    kServiceFieldNumber = 1,
    kMethodIdFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .com.mercedes_benz.csa.Service service = 1;
  bool has_service() const;
  void clear_service() ;
  const ::com::mercedes_benz::csa::Service& service() const;
  PROTOBUF_NODISCARD ::com::mercedes_benz::csa::Service* release_service();
  ::com::mercedes_benz::csa::Service* mutable_service();
  void set_allocated_service(::com::mercedes_benz::csa::Service* value);
  void unsafe_arena_set_allocated_service(::com::mercedes_benz::csa::Service* value);
  ::com::mercedes_benz::csa::Service* unsafe_arena_release_service();

  private:
  const ::com::mercedes_benz::csa::Service& _internal_service() const;
  ::com::mercedes_benz::csa::Service* _internal_mutable_service();

  public:
  // int32 method_id = 2;
  void clear_method_id() ;
  ::int32_t method_id() const;
  void set_method_id(::int32_t value);

  private:
  ::int32_t _internal_method_id() const;
  void _internal_set_method_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:com.mercedes_benz.csa.Method)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Method_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Method& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::com::mercedes_benz::csa::Service* service_;
    ::int32_t method_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_adapter_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Service

// int32 service_id = 1;
inline void Service::clear_service_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_id_ = 0;
}
inline ::int32_t Service::service_id() const {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Service.service_id)
  return _internal_service_id();
}
inline void Service::set_service_id(::int32_t value) {
  _internal_set_service_id(value);
  // @@protoc_insertion_point(field_set:com.mercedes_benz.csa.Service.service_id)
}
inline ::int32_t Service::_internal_service_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.service_id_;
}
inline void Service::_internal_set_service_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_id_ = value;
}

// int32 instance_id = 2;
inline void Service::clear_instance_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.instance_id_ = 0;
}
inline ::int32_t Service::instance_id() const {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Service.instance_id)
  return _internal_instance_id();
}
inline void Service::set_instance_id(::int32_t value) {
  _internal_set_instance_id(value);
  // @@protoc_insertion_point(field_set:com.mercedes_benz.csa.Service.instance_id)
}
inline ::int32_t Service::_internal_instance_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.instance_id_;
}
inline void Service::_internal_set_instance_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.instance_id_ = value;
}

// -------------------------------------------------------------------

// Services

// repeated .com.mercedes_benz.csa.Service services = 1;
inline int Services::_internal_services_size() const {
  return _internal_services().size();
}
inline int Services::services_size() const {
  return _internal_services_size();
}
inline void Services::clear_services() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.services_.Clear();
}
inline ::com::mercedes_benz::csa::Service* Services::mutable_services(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:com.mercedes_benz.csa.Services.services)
  return _internal_mutable_services()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>* Services::mutable_services()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:com.mercedes_benz.csa.Services.services)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_services();
}
inline const ::com::mercedes_benz::csa::Service& Services::services(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Services.services)
  return _internal_services().Get(index);
}
inline ::com::mercedes_benz::csa::Service* Services::add_services() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::com::mercedes_benz::csa::Service* _add = _internal_mutable_services()->Add();
  // @@protoc_insertion_point(field_add:com.mercedes_benz.csa.Services.services)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>& Services::services() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:com.mercedes_benz.csa.Services.services)
  return _internal_services();
}
inline const ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>&
Services::_internal_services() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.services_;
}
inline ::google::protobuf::RepeatedPtrField<::com::mercedes_benz::csa::Service>*
Services::_internal_mutable_services() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.services_;
}

// -------------------------------------------------------------------

// Method

// .com.mercedes_benz.csa.Service service = 1;
inline bool Method::has_service() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.service_ != nullptr);
  return value;
}
inline void Method::clear_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.service_ != nullptr) _impl_.service_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::com::mercedes_benz::csa::Service& Method::_internal_service() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::com::mercedes_benz::csa::Service* p = _impl_.service_;
  return p != nullptr ? *p : reinterpret_cast<const ::com::mercedes_benz::csa::Service&>(::com::mercedes_benz::csa::_Service_default_instance_);
}
inline const ::com::mercedes_benz::csa::Service& Method::service() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Method.service)
  return _internal_service();
}
inline void Method::unsafe_arena_set_allocated_service(::com::mercedes_benz::csa::Service* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.service_);
  }
  _impl_.service_ = reinterpret_cast<::com::mercedes_benz::csa::Service*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.mercedes_benz.csa.Method.service)
}
inline ::com::mercedes_benz::csa::Service* Method::release_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::com::mercedes_benz::csa::Service* released = _impl_.service_;
  _impl_.service_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::com::mercedes_benz::csa::Service* Method::unsafe_arena_release_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:com.mercedes_benz.csa.Method.service)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::com::mercedes_benz::csa::Service* temp = _impl_.service_;
  _impl_.service_ = nullptr;
  return temp;
}
inline ::com::mercedes_benz::csa::Service* Method::_internal_mutable_service() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.service_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::com::mercedes_benz::csa::Service>(GetArena());
    _impl_.service_ = reinterpret_cast<::com::mercedes_benz::csa::Service*>(p);
  }
  return _impl_.service_;
}
inline ::com::mercedes_benz::csa::Service* Method::mutable_service() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::com::mercedes_benz::csa::Service* _msg = _internal_mutable_service();
  // @@protoc_insertion_point(field_mutable:com.mercedes_benz.csa.Method.service)
  return _msg;
}
inline void Method::set_allocated_service(::com::mercedes_benz::csa::Service* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.service_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.service_ = reinterpret_cast<::com::mercedes_benz::csa::Service*>(value);
  // @@protoc_insertion_point(field_set_allocated:com.mercedes_benz.csa.Method.service)
}

// int32 method_id = 2;
inline void Method::clear_method_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_id_ = 0;
}
inline ::int32_t Method::method_id() const {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Method.method_id)
  return _internal_method_id();
}
inline void Method::set_method_id(::int32_t value) {
  _internal_set_method_id(value);
  // @@protoc_insertion_point(field_set:com.mercedes_benz.csa.Method.method_id)
}
inline ::int32_t Method::_internal_method_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_id_;
}
inline void Method::_internal_set_method_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_id_ = value;
}

// bytes data = 3;
inline void Method::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& Method::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.Method.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Method::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:com.mercedes_benz.csa.Method.data)
}
inline std::string* Method::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:com.mercedes_benz.csa.Method.data)
  return _s;
}
inline const std::string& Method::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Method::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* Method::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* Method::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:com.mercedes_benz.csa.Method.data)
  return _impl_.data_.Release();
}
inline void Method::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.mercedes_benz.csa.Method.data)
}

// -------------------------------------------------------------------

// MethodCallResponse

// bytes data = 1;
inline void MethodCallResponse::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& MethodCallResponse::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.mercedes_benz.csa.MethodCallResponse.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MethodCallResponse::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:com.mercedes_benz.csa.MethodCallResponse.data)
}
inline std::string* MethodCallResponse::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:com.mercedes_benz.csa.MethodCallResponse.data)
  return _s;
}
inline const std::string& MethodCallResponse::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void MethodCallResponse::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* MethodCallResponse::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* MethodCallResponse::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:com.mercedes_benz.csa.MethodCallResponse.data)
  return _impl_.data_.Release();
}
inline void MethodCallResponse::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.mercedes_benz.csa.MethodCallResponse.data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace csa
}  // namespace mercedes_benz
}  // namespace com


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_adapter_2eproto_2epb_2eh
