// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: adapter.proto

#include "adapter.pb.h"
#include "adapter.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace com {
namespace mercedes_benz {
namespace csa {

static const char* Adapter_method_names[] = {
  "/com.mercedes_benz.csa.Adapter/GetAvailableServices",
  "/com.mercedes_benz.csa.Adapter/CallMethod",
};

std::unique_ptr< Adapter::Stub> Adapter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Adapter::Stub> stub(new Adapter::Stub(channel, options));
  return stub;
}

Adapter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetAvailableServices_(Adapter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CallMethod_(Adapter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Adapter::Stub::GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::com::mercedes_benz::csa::Services* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAvailableServices_, context, request, response);
}

void Adapter::Stub::async::GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAvailableServices_, context, request, response, std::move(f));
}

void Adapter::Stub::async::GetAvailableServices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAvailableServices_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>* Adapter::Stub::PrepareAsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::com::mercedes_benz::csa::Services, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAvailableServices_, context, request);
}

::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::Services>* Adapter::Stub::AsyncGetAvailableServicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAvailableServicesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Adapter::Stub::CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::com::mercedes_benz::csa::MethodCallResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallMethod_, context, request, response);
}

void Adapter::Stub::async::CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallMethod_, context, request, response, std::move(f));
}

void Adapter::Stub::async::CallMethod(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallMethod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>* Adapter::Stub::PrepareAsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::com::mercedes_benz::csa::MethodCallResponse, ::com::mercedes_benz::csa::Method, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallMethod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::com::mercedes_benz::csa::MethodCallResponse>* Adapter::Stub::AsyncCallMethodRaw(::grpc::ClientContext* context, const ::com::mercedes_benz::csa::Method& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallMethodRaw(context, request, cq);
  result->StartCall();
  return result;
}

Adapter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Adapter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Adapter::Service, ::google::protobuf::Empty, ::com::mercedes_benz::csa::Services, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Adapter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::com::mercedes_benz::csa::Services* resp) {
               return service->GetAvailableServices(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Adapter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Adapter::Service, ::com::mercedes_benz::csa::Method, ::com::mercedes_benz::csa::MethodCallResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Adapter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::com::mercedes_benz::csa::Method* req,
             ::com::mercedes_benz::csa::MethodCallResponse* resp) {
               return service->CallMethod(ctx, req, resp);
             }, this)));
}

Adapter::Service::~Service() {
}

::grpc::Status Adapter::Service::GetAvailableServices(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::com::mercedes_benz::csa::Services* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Adapter::Service::CallMethod(::grpc::ServerContext* context, const ::com::mercedes_benz::csa::Method* request, ::com::mercedes_benz::csa::MethodCallResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace com
}  // namespace mercedes_benz
}  // namespace csa

