# Configuration file of DLT daemon
#
# Configurations made here will overwrite settings by command line

########################################################################
# General configuration                                                #
########################################################################

SendContextRegistration = 1
ECUId = ECUA
SharedMemorySize = 100000
LoggingMode = 0
LoggingLevel = 6
LoggingFilename = /tmp/dlt.log
TimeOutOnSend = 4
RingbufferMinSize = 500000
RingbufferMaxSize = 10000000
RingbufferStepSize = 500000

########################################################################
# Message Filter Configuration                                         #
########################################################################

MessageFilterConfigFile = /opt/vrte/dev-aap-dlt/etc/dlt_message_filter.conf

########################################################################
# Control Application                                                  #
########################################################################

ControlSocketPath = /opt/vrte/dev-aap-dlt/data/dlt-ctrl.sock

##############################################################################
# Offline logstorage                                                         #
##############################################################################

OfflineLogstorageMaxDevices = 1
OfflineLogstorageDirPath = /
OfflineLogstorageTimestamp = 0
OfflineLogstorageDelimiter = .
OfflineLogstorageOptionalIndex = 1

##############################################################################
# Application Specific settings                                              #
##############################################################################

AllowBlockMode = 1
